"""make game_id and favorite_themes nullable in user_survey

Revision ID: b3b1c5a7d9e2
Revises: 9173969e9706
Create Date: 2026-05-17 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b1c5a7d9e2'
down_revision = '9173969e9706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_survey', 'game_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    op.alter_column('user_survey', 'favorite_themes',
                    existing_type=sa.ARRAY(sa.String(length=50)),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_survey', 'favorite_themes',
                    existing_type=sa.ARRAY(sa.String(length=50)),
                    nullable=False)
    op.alter_column('user_survey', 'game_id',
                    existing_type=sa.Integer(),
                    nullable=False)
    # ### end Alembic commands ###
